import type { Concept } from "../schema";

const c = (
  id: string,
  name: string,
  layerId: string,
  description: string,
  problem: string,
  mechanism: string,
  tradeoffs: string,
  betterAlternative: string,
): Concept => ({ id, slug: id, name, layerId, description, problem, mechanism, tradeoffs, betterAlternative });

export const concepts: Concept[] = [
  // Application
  c("n-plus-one", "N+1 Queries", "application",
    "One query per row instead of one query per set.",
    "Latency grows linearly with result size.",
    "Lazy-loaded relations inside a loop issue a database round-trip per item.",
    "Eager loading can over-fetch rows and columns you never use.",
    "Batch with joins, IN-lists or a dataloader keyed by id."),
  c("unbounded-query", "Unbounded Query", "application",
    "A query with no LIMIT whose result grows with the data.",
    "Fine in development, catastrophic once a table reaches millions of rows.",
    "The whole result is materialised in database memory, on the wire and in the app heap.",
    "Limits force callers to handle partial results.",
    "Always paginate; enforce a hard maximum page size."),
  c("missing-pagination", "Missing Pagination", "application",
    "An endpoint returns every record in one response.",
    "Response size and latency grow without bound.",
    "Each request serialises the full collection and holds it in memory.",
    "Offset pagination gets slow on deep pages.",
    "Keyset (cursor) pagination on an indexed column."),
  c("hot-path-allocation", "Hot-Path Allocation", "application",
    "Creating many short-lived objects in code that runs per request.",
    "Throughput drops and tail latency rises under load.",
    "High allocation rate fills the young generation and forces frequent collections.",
    "Object pooling adds complexity and its own bugs.",
    "Reuse buffers, avoid boxing, profile allocations before optimising."),
  c("synchronous-fanout", "Synchronous Fan-out", "application",
    "One request calls many downstream services and waits for all of them.",
    "Overall latency is set by the slowest dependency.",
    "With N parallel calls, the chance of hitting at least one slow tail grows with N.",
    "Async designs are harder to reason about and debug.",
    "Reduce fan-out, set per-call deadlines, return partial results."),
  // API & Resilience
  c("retry-storm", "Retry Storm", "api",
    "Clients retry in lockstep and multiply load on a struggling service.",
    "A brief slowdown turns into a full outage.",
    "Every failure spawns more requests; retries at each layer multiply geometrically.",
    "Fewer retries mean more user-visible errors during blips.",
    "Exponential backoff with jitter, retry budgets, retry at one layer only."),
  c("thundering-herd", "Thundering Herd", "api",
    "Many waiting clients wake up and act at the same instant.",
    "A recovering service is knocked over the moment it comes back.",
    "A shared trigger (restart, expiry, timer) synchronises otherwise independent clients.",
    "Spreading load out delays some clients.",
    "Add jitter, stagger wake-ups, admit clients gradually."),
  c("missing-timeout", "Missing Timeout", "api",
    "A network call that can wait forever.",
    "One stuck dependency ties up threads and connections indefinitely.",
    "Without a deadline, slow responses hold resources until the caller's pool is empty.",
    "Timeouts that are too short cause spurious failures and retries.",
    "Set timeouts from measured p99.9 latency and propagate deadlines."),
  c("exponential-backoff", "Exponential Backoff with Jitter", "api",
    "Wait progressively longer, randomised intervals between retries.",
    "Fixed retry intervals keep clients synchronised.",
    "Doubling the delay sheds load; random jitter breaks synchronisation.",
    "Slower recovery for individual requests.",
    "Combine with a retry budget and circuit breaker."),
  c("circuit-breaker", "Circuit Breaker", "api",
    "Stop calling a dependency that keeps failing.",
    "Calls to a dead dependency waste resources and add latency.",
    "After an error threshold the breaker opens and fails fast, then probes to recover.",
    "Mis-tuned thresholds can trip on healthy services.",
    "Tune on error rate over a window, not absolute counts."),
  c("rate-limiting", "Rate Limiting", "api",
    "Cap how many requests a client may send per unit of time.",
    "One heavy client can starve everyone else.",
    "Token or leaky buckets admit bursts up to a limit and reject the rest.",
    "Legitimate spikes get rejected.",
    "Per-tenant limits with clear 429 responses and Retry-After headers."),
  c("idempotency-key", "Idempotency Keys", "api",
    "A client-supplied key that makes repeated requests safe.",
    "Retries can double-charge or duplicate writes.",
    "The server stores the key with the result and replays it for duplicates.",
    "Requires durable storage and a key expiry policy.",
    "Design write APIs to be naturally idempotent where possible."),
  c("bulkhead", "Bulkhead", "api",
    "Isolate resources per dependency so one failure cannot drain them all.",
    "A single slow dependency exhausts a shared pool.",
    "Separate thread or connection pools cap the blast radius of each dependency.",
    "Partitioned pools are less efficient when idle.",
    "Size bulkheads from each dependency's concurrency needs."),
  // Data
  c("connection-pool-exhaustion", "Connection Pool Exhaustion", "data",
    "Every database connection is checked out; new work waits.",
    "Requests time out even though the database looks idle.",
    "Slow queries or leaked connections hold slots longer than the arrival rate allows (Little's law).",
    "Bigger pools push contention into the database itself.",
    "Size pools by Little's law; fix slow queries; add a pooler."),
  c("lock-contention", "Lock Contention", "data",
    "Transactions wait on row or table locks held by others.",
    "Throughput collapses under concurrent writes to hot rows.",
    "Waiters queue behind lock holders; long holders create long queues.",
    "Optimistic concurrency moves the cost into retries.",
    "Shorten transactions, shard hot rows, prefer append-only writes."),
  c("missing-index", "Missing Index", "data",
    "A frequent query filters on a column with no index.",
    "Queries slow down as the table grows.",
    "The planner has no choice but to scan every row.",
    "Each index slows writes and uses storage.",
    "Index columns used in WHERE, JOIN and ORDER BY of hot queries."),
  c("full-table-scan", "Full Table Scan", "data",
    "The database reads every row to answer a query.",
    "Heavy I/O and CPU that evict useful pages from cache.",
    "Sequential reads of the entire table, often due to a missing or unusable index.",
    "For small tables or large result fractions a scan is actually cheaper.",
    "Check EXPLAIN; add or fix the index; rewrite non-sargable predicates."),
  c("long-transaction", "Long-Running Transaction", "data",
    "A transaction left open for seconds or minutes.",
    "Holds locks and blocks vacuum, bloating tables.",
    "Locks and old row versions are retained until commit.",
    "Splitting work loses atomicity.",
    "Keep transactions short; never wait on network calls inside one."),
  c("deadlock", "Deadlock", "data",
    "Two transactions each wait for a lock the other holds.",
    "One transaction is killed; under load this repeats constantly.",
    "Locks acquired in inconsistent order form a cycle.",
    "Coarser locking prevents deadlocks but reduces concurrency.",
    "Acquire locks in a consistent order; retry aborted transactions."),
  c("replication-lag", "Replication Lag", "data",
    "Replicas fall behind the primary.",
    "Users read stale data right after writing.",
    "Replicas apply the write log more slowly than the primary produces it.",
    "Reading from the primary loses the scaling benefit.",
    "Read-your-writes routing; monitor lag; throttle bulk writes."),
  c("connection-pooler", "Connection Pooler", "data",
    "A proxy (e.g. PgBouncer) that multiplexes many clients onto few connections.",
    "Each database connection costs memory and a process.",
    "Transaction-level pooling lends a server connection only while a transaction runs.",
    "Breaks session-level features like prepared statements in some modes.",
    "Use transaction pooling with session state kept in the app."),
  c("query-plan-regression", "Query Plan Regression", "data",
    "The planner suddenly picks a worse plan for an unchanged query.",
    "A query that took milliseconds now takes seconds.",
    "Stale statistics or parameter skew mislead the cost model.",
    "Pinning plans prevents adapting to data changes.",
    "Keep statistics fresh; capture plans; alert on plan changes."),
  c("write-amplification", "Write Amplification", "data",
    "One logical write causes many physical writes.",
    "Disks saturate well below expected throughput.",
    "Indexes, WAL, page splits and compaction each rewrite the data.",
    "Fewer indexes make reads slower.",
    "Drop unused indexes; batch writes; choose storage engines deliberately."),
  // Caching
  c("cache-stampede", "Cache Stampede", "caching",
    "A popular cache entry expires and every request recomputes it at once.",
    "The backing store is flooded the instant a key expires.",
    "All concurrent misses go to the origin before any of them repopulates the cache.",
    "Locking adds latency for waiters.",
    "Request coalescing, early probabilistic refresh, stale-while-revalidate."),
  c("request-coalescing", "Request Coalescing", "caching",
    "Merge identical in-flight requests into one.",
    "Duplicate work multiplies load during misses.",
    "The first request fetches; concurrent identical requests wait for its result.",
    "One slow fetch delays every waiter.",
    "Coalesce with a timeout and serve stale data when possible."),
  c("cold-cache", "Cold Cache", "caching",
    "A cache with nothing in it after a deploy or restart.",
    "Origin load spikes and latency jumps until the cache warms.",
    "Every request misses until the working set is reloaded.",
    "Pre-warming costs time during deploys.",
    "Warm caches before taking traffic; roll restarts gradually."),
  c("hot-key", "Hot Key", "caching",
    "A single key receives a disproportionate share of traffic.",
    "One shard or node saturates while others idle.",
    "Consistent hashing sends every request for the key to the same node.",
    "Replicating the key complicates invalidation.",
    "Local in-process caching or key splitting for hot entries."),
  c("cache-invalidation", "Cache Invalidation", "caching",
    "Removing or updating cached data when the source changes.",
    "Users see stale or inconsistent data.",
    "Writes and invalidations race; deletes can arrive before a stale refill.",
    "Short TTLs reduce staleness but increase origin load.",
    "Versioned keys or write-through with explicit TTL bounds."),
  // Runtime
  c("gc-pause", "GC Pause", "runtime",
    "The runtime stops application threads to reclaim memory.",
    "Tail latency spikes unrelated to request work.",
    "Heap pressure triggers stop-the-world collection phases.",
    "Larger heaps pause less often but can pause longer.",
    "Reduce allocation; use a low-pause collector; right-size the heap."),
  c("heap-pressure", "Heap Pressure", "runtime",
    "The live heap sits close to its maximum.",
    "Collections run constantly, eating CPU.",
    "Little free space means every allocation burst triggers a GC.",
    "Raising the heap limit risks the container's memory limit.",
    "Find what retains memory; reduce caches held in heap."),
  c("memory-leak", "Memory Leak", "runtime",
    "Memory that is never released.",
    "The process slows down and is eventually killed.",
    "Unbounded caches, listeners or global maps keep objects reachable.",
    "Periodic restarts hide the leak instead of fixing it.",
    "Heap snapshots over time; bound every cache."),
  c("thread-pool-starvation", "Thread Pool Starvation", "runtime",
    "Every worker thread is blocked.",
    "The service stops accepting work while CPU sits idle.",
    "Blocking I/O on a bounded pool parks all workers at once.",
    "Unbounded pools trade starvation for memory blowups.",
    "Async I/O or a separate bulkhead pool for blocking work."),
  c("event-loop-blocking", "Event Loop Blocking", "runtime",
    "CPU-heavy or synchronous work runs on a single-threaded event loop.",
    "Every concurrent request stalls together.",
    "Nothing else can run until the blocking task yields.",
    "Worker threads add serialisation and coordination cost.",
    "Move CPU work to workers; chunk long tasks."),
  c("async-io", "Async I/O", "runtime",
    "Non-blocking I/O that frees threads while waiting.",
    "Thread-per-request wastes threads waiting on I/O.",
    "The kernel signals readiness (epoll, io_uring); few threads serve many connections.",
    "Harder debugging and a risk of blocking the loop.",
    "Use async for I/O-bound services; keep CPU work off the loop."),
  // Network
  c("tcp-retransmits", "TCP Retransmits", "network",
    "Lost packets are resent after a timeout.",
    "Requests stall for hundreds of milliseconds.",
    "Packet loss triggers retransmission timeouts and shrinks the congestion window.",
    "Aggressive timeouts cause spurious retransmits.",
    "Fix the lossy link; tune minimum RTO; consider QUIC."),
  c("head-of-line-blocking", "Head-of-Line Blocking", "network",
    "One slow item at the front of a queue delays everything behind it.",
    "Unrelated requests on the same connection stall together.",
    "TCP delivers bytes in order; one lost packet blocks all multiplexed streams.",
    "More connections cost handshakes and memory.",
    "HTTP/3 (QUIC) independent streams; separate queues for slow work."),
  c("dns-latency", "DNS Resolution Latency", "network",
    "Time spent resolving hostnames before connecting.",
    "Sporadic slow requests with no server-side cause.",
    "Uncached lookups, resolver timeouts and search-domain expansion add round-trips.",
    "Long TTLs slow down failover.",
    "Local caching resolver; use fully-qualified names."),
  c("connection-churn", "Connection Churn", "network",
    "Opening and closing connections for each request.",
    "CPU and latency wasted on handshakes; ephemeral ports run out.",
    "Every new connection pays TCP and TLS setup and leaves a TIME_WAIT socket.",
    "Long-lived connections can pin load to one backend.",
    "Keep-alive and connection pooling."),
  c("keep-alive", "Connection Keep-Alive", "network",
    "Reuse one connection for many requests.",
    "Per-request handshakes add latency.",
    "Idle connections stay open and are reused by later requests.",
    "Stale connections fail if the server closes them silently.",
    "Match client idle timeouts below server timeouts."),
  c("tls-handshake-cost", "TLS Handshake Cost", "network",
    "Cryptographic setup before the first byte of data.",
    "Extra round-trips and CPU on every new connection.",
    "Key exchange and certificate validation take 1–2 RTTs and asymmetric crypto.",
    "Session resumption has replay considerations.",
    "TLS 1.3, session resumption and connection reuse."),
  // OS
  c("cpu-throttling", "CPU Throttling", "os",
    "The kernel caps a container's CPU time per period.",
    "Latency spikes despite low average CPU.",
    "The CFS quota is used up early in each 100 ms period, so threads wait for the next one.",
    "Removing limits risks noisy-neighbour effects.",
    "Raise the quota, reduce thread count, or use requests without limits."),
  c("context-switching", "Excessive Context Switching", "os",
    "The CPU spends its time switching between threads.",
    "High CPU usage with little useful work.",
    "Far more runnable threads than cores force the scheduler to swap constantly.",
    "Fewer threads can underuse cores during I/O waits.",
    "Size thread pools near core count for CPU-bound work."),
  c("fd-exhaustion", "File Descriptor Exhaustion", "os",
    "The process hits its open-file limit.",
    "New connections and file opens fail with EMFILE.",
    "Leaked sockets or many idle connections consume descriptors.",
    "Raising limits only delays a leak.",
    "Close resources reliably; raise ulimit to match expected load."),
  c("page-cache-thrashing", "Page Cache Thrashing", "os",
    "The working set does not fit in memory, so pages are constantly evicted.",
    "Disk I/O explodes and reads become slow.",
    "The kernel evicts pages that are needed again moments later.",
    "More memory costs money.",
    "Shrink the working set or add memory; avoid scans that pollute cache."),
  c("noisy-neighbor", "Noisy Neighbour", "os",
    "Another workload on the same host consumes shared resources.",
    "Unexplained performance swings.",
    "Shared CPU caches, memory bandwidth, disks and NICs are contended.",
    "Dedicated hosts cost more.",
    "Resource isolation, dedicated nodes for critical services."),
  // Distributed
  c("cascading-failure", "Cascading Failure", "distributed",
    "A failure in one component overloads others until the system collapses.",
    "A local problem becomes a site-wide outage.",
    "Load from a failed node shifts to survivors, which then fail too.",
    "Shedding load deliberately drops some users.",
    "Load shedding, circuit breakers, bulkheads and capacity headroom."),
  c("load-shedding", "Load Shedding", "distributed",
    "Deliberately rejecting work when overloaded.",
    "Accepting everything makes every request slow.",
    "Reject early and cheaply once queue length or latency crosses a threshold.",
    "Some requests are refused that might have succeeded.",
    "Prioritise critical traffic; shed lowest-priority first."),
  c("backpressure", "Backpressure", "distributed",
    "Signalling producers to slow down when consumers fall behind.",
    "Unbounded queues hide overload until memory runs out.",
    "Bounded buffers block or reject upstream when full.",
    "Producers must handle being slowed or rejected.",
    "Bound every queue; propagate pressure to the edge."),
  c("queue-buildup", "Queue Buildup", "distributed",
    "Work arrives faster than it is processed and queues grow.",
    "Latency climbs steadily, then requests time out.",
    "Once utilisation nears 100%, queueing delay grows sharply.",
    "Bigger queues only trade errors for latency.",
    "Bound queues; keep utilisation below saturation."),
  c("tail-latency", "Tail Latency", "distributed",
    "The slowest few percent of requests (p99, p99.9).",
    "At scale, most user requests touch at least one slow tail.",
    "GC, queuing, retransmits and contention create rare but large delays that fan-out amplifies.",
    "Optimising the tail costs extra capacity.",
    "Hedged requests, deadline propagation, fewer dependencies."),
  c("hedged-requests", "Hedged Requests", "distributed",
    "Send a duplicate request if the first is slow, and use whichever answers first.",
    "A single slow replica dictates latency.",
    "After a p95 delay a second copy goes to another replica; the loser is cancelled.",
    "Adds a few percent of extra load.",
    "Hedge only idempotent reads; cap the hedge rate."),
];
