import type { Evidence, EvidenceKind } from "../schema";

/**
 * Evidence authoring. Every card answers four questions:
 *   what you would see · where you would look · why it matters · how it lies.
 * Signal names follow OpenTelemetry semantic conventions where one exists,
 * and the native tool's own name otherwise (pg_stat_*, cgroup, netstat).
 */
const e = (
  id: string,
  conceptId: string,
  kind: EvidenceKind,
  trend: Evidence["trend"],
  signal: string,
  whatYouSee: string,
  whereToLook: string,
  whyItMatters: string,
  falsePositive?: string,
): Evidence => ({
  id,
  conceptId,
  kind,
  trend,
  signal,
  whatYouSee,
  whereToLook,
  whyItMatters,
  ...(falsePositive ? { falsePositive } : {}),
});

export const evidence: Evidence[] = [
  // ---------------------------------------------------------------- application
  e("ev-n1-trace", "n-plus-one", "TRACE", "UP",
    "db.statement span count per request",
    "Dozens of near-identical child spans under one request span, each a few milliseconds, each selecting a single row by id.",
    "A single slow trace in your tracing UI, sorted by span count rather than duration.",
    "Latency scales with the number of rows rendered, so the endpoint degrades silently as data grows rather than when traffic grows.",
    "A legitimate batch job can also issue many statements; check whether the statements differ only by a bound parameter."),
  e("ev-n1-metric", "n-plus-one", "METRIC", "UP",
    "db.client.operation.duration (count) / http.server.request.duration (count)",
    "Queries-per-request climbing from ~3 to ~60 after a release, while each query stays fast.",
    "A ratio panel of database call count over request count, grouped by route.",
    "The ratio isolates the N+1 from general traffic growth: the per-query time is innocent, the count is the bug.",
    "Adding a legitimate feature to a page also raises the ratio; compare against the deploy marker."),
  e("ev-unbounded-rows", "unbounded-query", "METRIC", "UP",
    "db.client.response.returned_rows",
    "Row counts for one query id creeping from hundreds to hundreds of thousands over weeks.",
    "Database statement statistics (pg_stat_statements.rows / calls) trended over time.",
    "An unbounded query is a time bomb: nothing changes in the code, the table simply grows past the point where the result fits comfortably in memory.",
    "A reporting query legitimately returns large results; check whether the caller is a user-facing route."),
  e("ev-unbounded-oom", "unbounded-query", "LOG", "PRESENT",
    "JavaScript heap out of memory / OOMKilled",
    "The process dies during a request that worked yesterday, and the restart happens under normal traffic.",
    "Container restart events and the last 200 log lines before exit code 137.",
    "Out-of-memory at a stable request rate points at result size, not concurrency.",
    "A memory leak produces the same crash; a leak grows between requests, an unbounded query spikes inside one."),
  e("ev-pagination-size", "missing-pagination", "METRIC", "UP",
    "http.server.response.body.size",
    "p99 response bodies measured in megabytes on a list endpoint while p50 is a few kilobytes.",
    "Response-size histogram for the route, not averages — the average hides it.",
    "Large responses cost serialisation CPU, bandwidth and client memory, and they make timeouts look random because only large accounts hit them.",
    "An export endpoint is supposed to be large; separate exports from browse endpoints."),
  e("ev-pagination-deep", "missing-pagination", "QUERY_PLAN", "UP",
    "EXPLAIN: Limit … Offset 50000",
    "A plan that scans and discards fifty thousand rows before returning twenty.",
    "EXPLAIN (ANALYZE, BUFFERS) on the deepest page your UI can reach.",
    "Offset pagination gets slower the further a user pages, which is why complaints come from your most engaged users.",
    "Shallow pages look fine; always test the deep page, not the first one."),
  e("ev-fanout-trace", "synchronous-fanout", "TRACE", "UP",
    "span.kind=client children per request",
    "A trace waterfall shaped like a comb: one parent, many sequential outbound calls, total time equal to their sum.",
    "The widest trace for the route, with the critical path highlighted.",
    "Sequential fan-out makes your availability the product of everyone else's, and your latency their sum.",
    "Parallel fan-out shows the same span count but overlapping bars; only the sequential shape is the problem."),
  e("ev-fanout-dependency", "synchronous-fanout", "METRIC", "UP",
    "http.client.request.duration by peer.service",
    "Your endpoint's error rate tracking another service's error rate exactly, with no lag.",
    "A correlation panel of your route's errors against each downstream dependency.",
    "Perfect correlation with no lag means you are calling it inline on the request path.",
    "A shared dependency (both of you calling the same database) produces correlation without a direct call."),
  e("ev-alloc-profile", "hot-path-allocation", "PROFILE", "UP",
    "allocation profile bytes by call site",
    "One request handler responsible for most of the allocated bytes, mostly short-lived strings and intermediate arrays.",
    "A heap allocation profile (pprof alloc_space, async-profiler alloc, --cpu-prof) taken under load.",
    "Allocation rate drives collection frequency, so this shows up as GC pauses in a part of the system that looks unrelated.",
    "Allocation is cheap in most runtimes; only act if GC pause time is actually significant."),

  // ---------------------------------------------------------- api & resilience
  e("ev-retry-log", "retry-storm", "LOG", "UP",
    "retry attempt=N of M",
    "Retry log lines growing several times faster than incoming request lines.",
    "A log rate panel filtered to the client library's retry message, overlaid on request rate.",
    "When retries grow faster than traffic, the client is amplifying an outage instead of riding it out.",
    "A single flaky dependency can raise retries without a storm; check whether the amplification is accelerating."),
  e("ev-retry-metric", "retry-storm", "METRIC", "SPIKE",
    "http.client.request.duration{http.request.resend_count>0}",
    "Attempts per logical call jumping from 1.0 to 3.0 within one scrape interval, all at once.",
    "Resend-count ratio broken down by client instance.",
    "Lockstep means the clients share a trigger: one downstream blip plus one synchronised retry policy.",
    "A deploy that changes retry configuration moves the baseline permanently rather than spiking it."),
  e("ev-herd-spike", "thundering-herd", "METRIC", "SPIKE",
    "http.server.request.count at fixed offsets",
    "Request spikes arriving at exact wall-clock boundaries — every minute, on the minute.",
    "High-resolution request rate (5s buckets); the pattern disappears at 1-minute resolution.",
    "Clock-aligned spikes mean clients are coordinating by accident, usually through a cron or a shared cache TTL.",
    "A real traffic pattern can be periodic too; the giveaway is the sharpness of the edge."),
  e("ev-herd-recovery", "thundering-herd", "LOG", "SPIKE",
    "connection established after reconnect",
    "Every client reconnecting in the same second after a restart, saturating the service it just rejoined.",
    "Connection-accept logs during the minute after a restart or failover.",
    "Recovery is the most dangerous moment: the herd arrives exactly when the service is coldest.",
    "A rolling restart also concentrates reconnects; stagger it before blaming the clients."),
  e("ev-timeout-span", "missing-timeout", "TRACE", "UP",
    "span duration with no deadline attribute",
    "Client spans that run for minutes and end in cancellation, not response.",
    "Traces filtered to duration greater than your SLO, sorted descending.",
    "A call with no timeout turns a slow dependency into a leaked worker — the request never fails, it just occupies capacity.",
    "A streaming or long-poll endpoint is legitimately long-lived; exclude it by route."),
  e("ev-timeout-threads", "missing-timeout", "METRIC", "UP",
    "in-flight requests vs. request rate",
    "In-flight count rising while throughput stays flat or falls.",
    "A concurrency gauge next to a throughput counter on the same panel.",
    "By Little's Law, concurrency equals rate times latency — flat rate with rising concurrency means work is parking, not finishing.",
    "A deliberate concurrency increase (bigger pool) also raises the gauge; compare with configuration changes."),
  e("ev-breaker-state", "circuit-breaker", "METRIC", "PRESENT",
    "circuit.breaker.state (closed/open/half_open)",
    "A state timeline that opens within seconds of a dependency failing and probes back to closed afterwards.",
    "A state gauge per breaker, as a discrete timeline rather than an average.",
    "This is the evidence that protection actually engaged; a breaker nobody can see is a breaker nobody trusts.",
    "A breaker that flaps between open and half-open every few seconds is misconfigured, not protective."),
  e("ev-ratelimit-429", "rate-limiting", "METRIC", "UP",
    "http.server.request.count{http.response.status_code=429}",
    "429 responses concentrated on a handful of API keys while everyone else is unaffected.",
    "Status-code breakdown grouped by client identity.",
    "Rate limiting is only working if it is selective: broad 429s mean the limit is too low or the key is too coarse.",
    "A shared gateway key makes many tenants look like one noisy client."),
  e("ev-bulkhead-isolation", "bulkhead", "METRIC", "FLAT",
    "pool utilisation by partition",
    "One partition pinned at 100% while the others stay at their normal level and keep serving.",
    "Per-pool saturation panels on a single shared axis.",
    "Containment is the whole point: the evidence of a working bulkhead is a flat line next to a saturated one.",
    "Low overall traffic also produces flat lines; confirm the failing partition is genuinely saturated."),

  // ------------------------------------------------------------------ data
  e("ev-pool-metric", "connection-pool-exhaustion", "METRIC", "UP",
    "db.client.connection.pending_requests",
    "Pending acquisitions climbing while connection usage sits exactly at the configured maximum.",
    "Pool metrics from the driver: usage, idle, pending, all on one panel.",
    "Usage pinned at max with a queue behind it is the unambiguous signature; latency is then pure queueing, not database work.",
    "A pool that is merely busy shows usage at max with an empty queue — that is healthy saturation."),
  e("ev-pool-wait", "connection-pool-exhaustion", "TRACE", "UP",
    "connection acquisition span duration",
    "A long 'acquire connection' span in front of a fast query span.",
    "Trace detail for a slow request, looking at the gap before the database span starts.",
    "It separates waiting for a connection from waiting for the database — two problems with opposite fixes.",
    "Driver instrumentation sometimes folds acquisition into the query span, hiding the wait entirely."),
  e("ev-pool-timeout-log", "connection-pool-exhaustion", "LOG", "PRESENT",
    "timeout acquiring connection from pool",
    "Acquisition timeouts appearing in bursts, often right after a slow-query incident.",
    "Application error logs filtered to the pool's timeout message.",
    "The log line names the real constraint, which is otherwise reported to users as a generic 500.",
    "A pool configured with an unrealistically short acquire timeout produces these under normal load."),
  e("ev-lock-counter", "lock-contention", "METRIC", "UP",
    "pg_locks where granted = false",
    "A growing population of ungranted locks, all waiting on the same relation or row.",
    "A periodic query over pg_locks joined to pg_stat_activity, grouped by relation.",
    "It names the exact object everyone is queueing for, which turns a vague 'database is slow' into a specific hot row.",
    "Brief spikes during a migration or bulk load are expected; sustained growth is not."),
  e("ev-lock-wait-log", "lock-contention", "LOG", "PRESENT",
    "process still waiting for ShareLock after 1000 ms",
    "Lock-wait warnings naming a blocking process id and the statement it is running.",
    "Database server log with log_lock_waits enabled.",
    "It identifies the blocker, not just the victim — the victim is the one complaining, the blocker is the one to fix.",
    "An administrative statement such as a long ALTER can block everything briefly and legitimately."),
  e("ev-index-plan", "missing-index", "QUERY_PLAN", "UP",
    "EXPLAIN: Rows Removed by Filter",
    "A plan node that reads a million rows and keeps twelve.",
    "EXPLAIN (ANALYZE, BUFFERS) on the slowest statement from pg_stat_statements.",
    "The ratio of rows read to rows returned is the cleanest statement of wasted work in the whole system.",
    "On a small table a sequential scan is correct and cheaper than an index; the ratio only matters at scale."),
  e("ev-index-seqscan", "missing-index", "METRIC", "UP",
    "pg_stat_user_tables.seq_scan vs idx_scan",
    "A large table whose sequential-scan counter rises steadily while its index-scan counter stays near zero.",
    "Table-level statistics sorted by seq_tup_read.",
    "It finds missing indexes across the whole database at once, instead of one slow query at a time.",
    "Append-only tables scanned by analytics jobs will always look like this; check who is querying."),
  e("ev-scan-plan", "full-table-scan", "QUERY_PLAN", "PRESENT",
    "EXPLAIN: Seq Scan on large_table",
    "A sequential scan under a selective filter, with the estimated and actual row counts far apart.",
    "EXPLAIN ANALYZE, comparing the estimate in parentheses with the actual rows.",
    "A bad estimate usually means stale statistics, which is a different fix from adding an index.",
    "A scan chosen for a query that genuinely touches most of the table is the right plan."),
  e("ev-scan-io", "full-table-scan", "OS_COUNTER", "UP",
    "disk read throughput (MB/s) on the database host",
    "Read throughput saturating the volume's limit while CPU stays moderate.",
    "Host or volume I/O metrics on the database instance.",
    "It shows the scan is actually leaving the page cache and hitting storage, which is the difference between slow and catastrophic.",
    "A backup, a vacuum or a replica rebuild produces the same read profile."),
  e("ev-longtx-age", "long-transaction", "METRIC", "UP",
    "max(now() - xact_start)",
    "A transaction age that keeps climbing — minutes, then hours — usually from one connection.",
    "pg_stat_activity, sorted by transaction start time.",
    "Long transactions hold snapshots that block vacuum, so a single forgotten BEGIN slowly degrades the whole database.",
    "A legitimate long-running migration or analytical query also shows up; check the statement text."),
  e("ev-longtx-idle", "long-transaction", "LOG", "PRESENT",
    "idle in transaction",
    "Connections sitting in 'idle in transaction' for minutes with no statement running.",
    "pg_stat_activity.state, or the server log with log_min_duration_statement set.",
    "Idle-in-transaction means the application opened a transaction and then went off to do something else — usually an HTTP call.",
    "Interactive database sessions from a human are harmless; filter by application_name."),
  e("ev-deadlock-log", "deadlock", "LOG", "PRESENT",
    "deadlock detected / Process A waits for … Process B waits for",
    "A deadlock report naming two processes and the exact statements that formed the cycle.",
    "Database server log; deadlocks are always logged with the full wait graph.",
    "The wait graph tells you the lock ordering to change; no other signal gives you the cycle itself.",
    "A single isolated deadlock under heavy concurrency can be normal; the rate is what matters."),
  e("ev-deadlock-rate", "deadlock", "METRIC", "UP",
    "pg_stat_database.deadlocks",
    "A deadlock counter that increments every few minutes instead of every few weeks.",
    "Database-wide statistics, as a rate rather than a total.",
    "A rising rate means a code path is acquiring locks in inconsistent order, and it will get worse with traffic.",
    "A batch job that runs hourly can concentrate deadlocks into predictable windows."),
  e("ev-replag-seconds", "replication-lag", "METRIC", "UP",
    "pg_last_xact_replay_timestamp lag in seconds",
    "Replica lag growing during write bursts and taking minutes to recover afterwards.",
    "Per-replica lag panels, with write throughput on the same chart.",
    "Lag is the window during which reads are wrong; its shape tells you whether the replica is bandwidth-bound or apply-bound.",
    "A paused or disconnected replica reports enormous lag that is a connectivity problem, not a throughput one."),
  e("ev-replag-readback", "replication-lag", "LOG", "PRESENT",
    "record not found immediately after create",
    "Not-found errors on a resource the user just created, resolving on refresh.",
    "Application error logs correlated with the replica lag panel.",
    "This is lag expressed as a user-visible bug, and it is the fastest way to convince a team the lag is real.",
    "A genuine race between two services can look identical; check whether the read hit a replica."),
  e("ev-plan-regression", "query-plan-regression", "QUERY_PLAN", "PRESENT",
    "plan node change for a stable query id",
    "The same query id switching from Index Scan to Bitmap Heap Scan, with no code change.",
    "Captured plans before and after the slowdown, diffed node by node.",
    "It proves the query did not change — the planner's mind did, usually because statistics or parameters changed.",
    "A schema change deployed at the same time can be the real cause; check migration history."),
  e("ev-plan-steptime", "query-plan-regression", "METRIC", "UP",
    "pg_stat_statements.mean_exec_time",
    "A step change in mean execution time for one query id — flat, then suddenly ten times higher, then flat again.",
    "Per-statement mean time trended, with ANALYZE and deploy markers overlaid.",
    "Step changes point at planning; gradual rises point at data growth. The shape distinguishes them.",
    "A change in parameter distribution (one huge tenant) produces the same step without any plan change."),
  e("ev-writeamp-wal", "write-amplification", "METRIC", "UP",
    "WAL bytes written per logical row written",
    "Ten kilobytes of write-ahead log for a hundred-byte update.",
    "WAL generation rate divided by application write rate.",
    "It quantifies how much hidden work each logical write creates — full-page images, index maintenance, replication traffic.",
    "The first write to a page after a checkpoint always logs the full page; measure across a checkpoint cycle."),

  // ----------------------------------------------------------------- caching
  e("ev-stampede-origin", "cache-stampede", "METRIC", "SPIKE",
    "origin request rate at cache expiry",
    "A vertical spike in backend requests at the exact second a popular key expires, then silence.",
    "Backend request rate at 1-second resolution, aligned with cache TTL boundaries.",
    "The spike is instantaneous and periodic — unmistakable once you look at the right resolution.",
    "A scheduled cache warm-up produces a similar spike on purpose."),
  e("ev-stampede-dup", "cache-stampede", "TRACE", "UP",
    "identical cache miss spans in flight",
    "Hundreds of concurrent traces, all missing the same key, all recomputing the same value.",
    "Traces filtered to the miss path, grouped by cache key.",
    "Seeing the same key in hundreds of simultaneous traces is the difference between 'the cache is cold' and 'the cache is stampeding'.",
    "A cold start after a deploy produces many misses across many different keys, not one key."),
  e("ev-coldcache-ratio", "cold-cache", "METRIC", "DOWN",
    "cache hit ratio",
    "Hit ratio collapsing to near zero at a deploy marker and climbing back over several minutes.",
    "Hit-ratio panel with deployment annotations.",
    "The recovery curve tells you how long the service is fragile after every restart — that is your real deploy risk window.",
    "A cache key format change empties the cache logically without any restart."),
  e("ev-hotkey-ops", "hot-key", "METRIC", "UP",
    "ops per key / per shard",
    "One key or shard taking a large share of all operations while the rest of the cluster idles.",
    "Per-shard operation rate, plus the cache's own hot-key report (redis-cli --hotkeys, MONITOR sampling).",
    "Sharding only helps if load spreads; a single hot key turns a distributed cache back into one server.",
    "A monitoring agent polling one key can look like application traffic."),
  e("ev-hotkey-cpu", "hot-key", "OS_COUNTER", "UP",
    "single-core CPU on one cache node",
    "One node's CPU at 100% while its siblings sit at 10%, with similar memory usage.",
    "Per-node CPU across the cache cluster on a shared axis.",
    "Cache servers are usually single-threaded per shard, so a hot key shows up as one saturated core, not high average CPU.",
    "An unbalanced shard map causes the same asymmetry without any single hot key."),
  e("ev-invalidation-stale", "cache-invalidation", "LOG", "PRESENT",
    "stale read detected / version mismatch",
    "Reads returning a version older than the last write, clustered just after writes.",
    "Application-level version checks logged on read, compared against write timestamps.",
    "Staleness is invisible in cache metrics — hit ratio looks great while the answers are wrong.",
    "Clock skew between writer and reader can fake a version mismatch."),

  // ----------------------------------------------------------------- runtime
  e("ev-gc-metric", "gc-pause", "METRIC", "SPIKE",
    "process.runtime.gc.duration",
    "Pause spikes that line up exactly with p99 latency spikes, while p50 stays flat.",
    "GC pause histogram overlaid on request latency percentiles.",
    "If the two spike together, latency is a runtime problem, and no amount of query tuning will fix it.",
    "A stop-the-world pause from a heap dump or a profiler attach looks identical."),
  e("ev-gc-frequency", "gc-pause", "METRIC", "UP",
    "collections per minute by generation",
    "Young collections every few hundred milliseconds, old collections several times a minute.",
    "Collection counters split by generation.",
    "Frequency separates allocation pressure (young) from a sizing or leak problem (old) — different fixes entirely.",
    "A deliberately small heap trades frequent cheap collections for memory; that can be fine."),
  e("ev-heap-pressure", "heap-pressure", "METRIC", "UP",
    "heap used after full collection",
    "The floor of the sawtooth rising release after release, even though the peaks look unchanged.",
    "Heap usage over hours, reading the post-collection minimum rather than the peak.",
    "Live-set size is the honest number; peak heap tells you about allocation, not about what the process actually retains.",
    "A cache that legitimately fills to a bounded size raises the floor once and then holds."),
  e("ev-heap-rss", "heap-pressure", "OS_COUNTER", "UP",
    "container memory.current vs memory.max",
    "Resident memory approaching the container limit while the runtime heap reports plenty of headroom.",
    "cgroup memory statistics next to runtime heap metrics.",
    "Off-heap memory — buffers, native libraries, thread stacks — is invisible to the runtime and is what actually gets you killed.",
    "Page cache counted inside the cgroup can inflate the number without real pressure."),
  e("ev-leak-profile", "memory-leak", "PROFILE", "UP",
    "heap snapshot retained size by type",
    "One type's retained size growing across three snapshots taken an hour apart, with a clear dominator path.",
    "Comparative heap snapshots, sorted by retained size delta.",
    "The dominator path names the object that is holding the garbage alive — that is the actual bug, not the leaked object.",
    "A deliberately unbounded in-memory cache is a leak by any other name; decide which one you have."),
  e("ev-leak-restart", "memory-leak", "LOG", "PRESENT",
    "OOMKilled / exit code 137 on a fixed cadence",
    "Restarts arriving at regular intervals, the interval shortening as traffic grows.",
    "Container restart history across all replicas.",
    "A predictable sawtooth of restarts is the signature of a leak; a crash under peak load is usually something else.",
    "A memory limit set below real working-set size produces regular kills without any leak."),
  e("ev-threadpool-queue", "thread-pool-starvation", "METRIC", "UP",
    "executor queue depth",
    "Queue depth growing while active threads sit at maximum and CPU stays low.",
    "Executor metrics: active, queued, completed, on one panel.",
    "Max threads plus idle CPU means the threads are blocked on I/O, not doing work — adding threads buys a little time, fixing the blocking call fixes it.",
    "A deliberately bounded pool in front of a slow dependency will queue by design."),
  e("ev-threadpool-wait", "thread-pool-starvation", "TRACE", "UP",
    "queue wait time before handler span",
    "A long gap between request receipt and the first application span.",
    "Trace timeline for a slow request, measuring the gap at the start.",
    "It splits total latency into waiting-to-start and actually-running, which is the first fork in every latency investigation.",
    "Clock skew between the receiving proxy and the application can fabricate a gap."),
  e("ev-eventloop-lag", "event-loop-blocking", "METRIC", "UP",
    "event loop lag / utilisation",
    "Loop lag jumping to hundreds of milliseconds while CPU is not saturated.",
    "Runtime event-loop metrics at high resolution.",
    "In a single-threaded runtime, loop lag is latency for every concurrent request — one slow synchronous call taxes all of them.",
    "A long garbage collection pause registers as loop lag too."),
  e("ev-eventloop-profile", "event-loop-blocking", "PROFILE", "PRESENT",
    "CPU profile: long synchronous frame",
    "A single frame — JSON parsing, crypto, a big sort — holding the stack for tens of milliseconds.",
    "A CPU profile captured during a lag spike, read as a flame graph.",
    "It names the exact function to make asynchronous or move off the main thread.",
    "Profilers attribute inlined native work oddly; verify with a second capture."),
  e("ev-asyncio-density", "async-io", "METRIC", "UP",
    "in-flight requests per OS thread",
    "Thousands of concurrent connections served by a handful of threads, with memory flat.",
    "Concurrency gauge divided by the runtime's thread count.",
    "High density is the entire payoff of async I/O: if it is near one, you have paid the complexity and kept the thread-per-request cost.",
    "Idle keep-alive connections inflate the numerator without representing real concurrency."),
  e("ev-asyncio-offcpu", "async-io", "PROFILE", "PRESENT",
    "off-CPU profile: threads parked in epoll_wait / kqueue",
    "Worker threads waiting in the event notification syscall rather than inside a blocking read.",
    "An off-CPU or wall-clock profile captured under load.",
    "It proves the I/O is really non-blocking; one accidental synchronous call shows up here as a thread parked in read() instead.",
    "Thread pools used for file I/O legitimately block, even in a fully async runtime."),

  // ----------------------------------------------------------------- network
  e("ev-retx-packet", "tcp-retransmits", "PACKET", "PRESENT",
    "TCP retransmission / duplicate ACK",
    "The same segment sent again after a retransmission timeout, often in bursts.",
    "A short packet capture on the sending host, filtered with tcp.analysis.retransmission.",
    "Retransmits explain latency that no application metric can account for — the request simply was not delivered.",
    "Capture-point artefacts (offload, mirrored ports) can show phantom retransmits."),
  e("ev-retx-os", "tcp-retransmits", "OS_COUNTER", "UP",
    "netstat -s TcpRetransSegs / TcpExtTCPLostRetransmit",
    "Retransmitted segments rising as a fraction of segments sent, on one host or one path.",
    "Kernel network statistics sampled as a rate, compared between hosts.",
    "It is cheap to collect everywhere, so it tells you whether the loss is one host, one availability zone, or the whole path.",
    "A noisy client network inflates the counter for traffic you do not control."),
  e("ev-holb-queue", "head-of-line-blocking", "METRIC", "UP",
    "time to first byte with flat server processing time",
    "Client-side latency rising while server-side handler time stays flat.",
    "Client and server latency for the same call, plotted together.",
    "A gap that grows between client and server time is queueing somewhere in between — connection, proxy or kernel.",
    "Clock skew between client and server can manufacture or hide the gap."),
  e("ev-dns-span", "dns-latency", "TRACE", "SPIKE",
    "DNS resolution span duration",
    "Occasional resolution spans of exactly five seconds — the classic resolver timeout — inside otherwise fast requests.",
    "Traces filtered to the client call, with resolution instrumented separately.",
    "Round numbers like 5s are timeouts, not work; they identify a retry at the resolver rather than a slow network.",
    "Many clients cache DNS internally, so the spans appear only on cold connections."),
  e("ev-dns-log", "dns-latency", "LOG", "PRESENT",
    "EAI_AGAIN / temporary failure in name resolution",
    "Resolution failures bursting across many pods at once.",
    "Application error logs, grouped by node rather than by service.",
    "Clustering by node distinguishes a broken local resolver cache from an upstream DNS outage.",
    "A misspelled hostname in a new release produces the same error permanently, not in bursts."),
  e("ev-churn-timewait", "connection-churn", "OS_COUNTER", "UP",
    "sockets in TIME_WAIT",
    "Tens of thousands of sockets in TIME_WAIT on a client host, with ephemeral ports running out.",
    "ss -s or netstat -an summarised by state.",
    "Each new connection costs a handshake and a port; churn turns a cheap call into an expensive one and eventually fails outright.",
    "A load generator legitimately opens short-lived connections; compare against production clients."),
  e("ev-churn-rate", "connection-churn", "METRIC", "UP",
    "new connections per second vs requests per second",
    "A connection-to-request ratio near one, where it should be near zero.",
    "Connection-accept rate over request rate at the server or proxy.",
    "The ratio is the direct measure of connection reuse; anything near one means keep-alive is not working.",
    "A proxy terminating and re-establishing connections can shift the ratio without any client change."),
  e("ev-keepalive-reuse", "keep-alive", "METRIC", "UP",
    "connection reuse ratio",
    "Requests per connection in the hundreds, with a stable pool of established sockets.",
    "Client pool metrics: created, reused, closed.",
    "High reuse is the evidence that handshake cost has actually been eliminated rather than merely hidden.",
    "A long-lived connection to a dead peer also looks reused until the first failure."),
  e("ev-tls-span", "tls-handshake-cost", "TRACE", "UP",
    "TLS handshake span duration",
    "Twenty to one hundred milliseconds of handshake in front of a two-millisecond call, on the first request only.",
    "A trace of a cold request, with connect and TLS phases instrumented.",
    "Handshake cost is paid per connection, so it is invisible in averages and dominant in cold-start and health-check traffic.",
    "Session resumption makes subsequent handshakes much cheaper; measure cold and warm separately."),
  e("ev-tls-cpu", "tls-handshake-cost", "OS_COUNTER", "UP",
    "CPU time in crypto routines",
    "A measurable share of total CPU in asymmetric crypto on a service with modest traffic.",
    "A CPU profile on the terminating proxy, grouped by library.",
    "Handshakes are the expensive part of TLS; bulk encryption is nearly free. This separates the two.",
    "Hardware acceleration can make the cost disappear from profiles while remaining in latency."),

  // ---------------------------------------------------------- operating system
  e("ev-throttle-os", "cpu-throttling", "OS_COUNTER", "UP",
    "cgroup cpu.stat nr_throttled / throttled_usec",
    "Throttled periods accumulating while average CPU utilisation looks comfortable, around 60%.",
    "cgroup v2 cpu.stat on the node, per container.",
    "Average utilisation hides throttling completely: the quota is enforced per 100 ms period, so a bursty service is throttled at low averages.",
    "A very low CPU request with bursty traffic will always throttle a little; look at the proportion of periods affected."),
  e("ev-throttle-latency", "cpu-throttling", "METRIC", "UP",
    "p99 latency correlated with throttled periods",
    "Latency steps that line up exactly with throttling, in 100-millisecond quanta.",
    "Throttled time and latency percentiles on one chart.",
    "The quantised shape is distinctive — it proves the delay is quota enforcement rather than contention.",
    "A noisy neighbour produces similar latency without any throttling counter movement."),
  e("ev-ctxsw-rate", "context-switching", "OS_COUNTER", "UP",
    "context switches per second (voluntary vs involuntary)",
    "Hundreds of thousands of switches per second, mostly involuntary, with system CPU time rising.",
    "vmstat or /proc/stat, split into voluntary and involuntary.",
    "Involuntary switches mean too many runnable threads for the cores available — the fix is fewer threads, not more.",
    "Voluntary switches are just I/O waits and are entirely normal."),
  e("ev-ctxsw-runqueue", "context-switching", "OS_COUNTER", "UP",
    "run queue length vs core count",
    "A run queue several times longer than the number of available cores, sustained.",
    "Load average and run queue depth, compared with the container's CPU allocation.",
    "Queue length relative to cores is the honest saturation measure; load average alone is nearly meaningless in containers.",
    "Processes in uninterruptible I/O sleep inflate load average on Linux without consuming CPU."),
  e("ev-fd-log", "fd-exhaustion", "LOG", "PRESENT",
    "EMFILE: too many open files",
    "Accept or open calls failing while the process keeps running and serving existing connections.",
    "Application error logs; the failure is usually in the accept loop.",
    "The error names a hard limit, so it is one of the few log lines that tells you the fix directly.",
    "A low ulimit inherited from the container image causes this at trivial concurrency."),
  e("ev-fd-counter", "fd-exhaustion", "OS_COUNTER", "UP",
    "open file descriptors vs RLIMIT_NOFILE",
    "Descriptor count climbing monotonically and never returning to baseline between traffic peaks.",
    "/proc/<pid>/fd count against the process limit, trended.",
    "Monotonic growth distinguishes a descriptor leak from a legitimately busy server.",
    "A connection pool that is warming up grows once and then plateaus."),
  e("ev-pagecache-faults", "page-cache-thrashing", "OS_COUNTER", "UP",
    "major page faults per second",
    "Major faults rising sharply while minor faults stay normal, with disk reads following.",
    "/proc/vmstat pgmajfault, next to block-device read throughput.",
    "Major faults mean the working set no longer fits in memory, which turns memory-speed access into disk-speed access.",
    "The first run after a restart always faults as the cache fills."),
  e("ev-pagecache-io", "page-cache-thrashing", "METRIC", "UP",
    "read IOPS with stable logical read rate",
    "Physical reads climbing while the application's logical read rate is unchanged.",
    "Database buffer-cache hit ratio alongside device-level IOPS.",
    "Constant logical reads with rising physical reads is caching failure, not increased demand.",
    "A competing process on the same host can evict your cache without any change in your workload."),
  e("ev-noisy-steal", "noisy-neighbor", "OS_COUNTER", "UP",
    "CPU steal time",
    "Steal time of several percent on one instance and near zero on its identical siblings.",
    "Per-instance CPU breakdown including steal, compared across the fleet.",
    "Steal is time the hypervisor gave to someone else — proof the problem is outside your process.",
    "Burstable instance types that have exhausted their credits show similar symptoms through a different mechanism."),
  e("ev-noisy-variance", "noisy-neighbor", "METRIC", "UP",
    "p99 latency variance across identical replicas",
    "One replica consistently slower than the rest while serving identical traffic and running identical code.",
    "Per-replica latency percentiles on a single panel.",
    "Identical code plus identical traffic plus different latency means the difference is the host, not the software.",
    "Uneven load balancing produces the same picture; check per-replica request rate first."),

  // ------------------------------------------------------- distributed systems
  e("ev-queue-depth", "queue-buildup", "METRIC", "UP",
    "queue depth and oldest message age",
    "Depth rising steadily and the oldest message ageing past the point where processing it is still useful.",
    "Broker metrics: depth, consumer lag, oldest-message age.",
    "Age matters more than depth: a deep queue that drains fast is fine, a shallow queue of stale work is not.",
    "A deliberate buffer in front of a batch consumer is supposed to be deep."),
  e("ev-queue-ratio", "queue-buildup", "METRIC", "DOWN",
    "consumer throughput / producer throughput",
    "A ratio below one, sustained, with no recovery during traffic troughs.",
    "Producer and consumer rates on the same panel.",
    "A ratio below one for long enough has only one ending; the trough is where you find out whether it is temporary.",
    "A consumer restart causes a brief dip that recovers on its own."),
  e("ev-tail-ratio", "tail-latency", "METRIC", "UP",
    "p99 / p50 ratio",
    "A ratio climbing from 3 to 30 while the median does not move at all.",
    "Latency percentiles as a ratio panel, not as separate lines.",
    "The ratio isolates variance from slowness; it is the single best early warning of saturation anywhere in the stack.",
    "Mixing fast and slow endpoints in one aggregate produces a high ratio with no underlying problem."),
  e("ev-tail-slowest", "tail-latency", "TRACE", "PRESENT",
    "slowest traces grouped by waiting phase",
    "The slowest 1% of traces sharing one phase — queueing, a lock, a retry — while the rest of the span tree is normal.",
    "Trace search sorted by duration, grouped by the dominant span.",
    "Tail latency almost always has one cause; the fastest way to find it is to read the tail itself rather than the average.",
    "Sampling often discards slow traces; make sure tail-based sampling is enabled before concluding anything."),
  e("ev-cascade-spread", "cascading-failure", "METRIC", "UP",
    "error rate by service over time",
    "Errors appearing in one service and then in its callers, tens of seconds apart, spreading outward.",
    "A service-level error-rate heatmap ordered by dependency depth.",
    "The time offsets reveal the direction of propagation, which tells you where the origin is rather than where the noise is loudest.",
    "A shared dependency failing makes everything fail simultaneously, with no offset — that is a different failure mode."),
  e("ev-cascade-saturation", "cascading-failure", "METRIC", "UP",
    "concurrency saturation across services",
    "Thread pools and connection pools reaching their limits one after another, in dependency order.",
    "Saturation panels for every service, stacked in call order.",
    "Cascades propagate through resource exhaustion, so saturation spreads before errors do — it is the earlier signal.",
    "A coordinated deploy can saturate several services at once without any cascade."),
  e("ev-shed-count", "load-shedding", "METRIC", "UP",
    "shed requests / 503 with Retry-After",
    "A plateau of shed requests while accepted requests hold a steady, serviceable rate.",
    "Accepted and shed counters on one stacked panel.",
    "Shedding is working when the accepted line stays flat and fast; if accepted latency rises too, the threshold is set too high.",
    "A proxy returning 503 for its own reasons looks the same from outside."),
  e("ev-backpressure-block", "backpressure", "METRIC", "UP",
    "producer blocked time / stream pause events",
    "Producers spending measurable time blocked, with queue depth bounded and stable.",
    "Stream or channel instrumentation on the producing side.",
    "Blocked producers with a bounded queue is backpressure working; unbounded growth with happy producers is backpressure missing.",
    "A slow producer that is never blocked may simply be upstream-limited."),
  e("ev-hedge-duplicates", "hedged-requests", "METRIC", "UP",
    "duplicate request ratio",
    "A few percent of requests sent twice, with the p99 dropping and the p50 unchanged.",
    "Hedge counter over total requests, next to latency percentiles.",
    "Hedging is only worth it if the extra load is small and the tail actually improves — both numbers have to be on the same screen.",
    "A hedge rate above ten percent usually means the trigger threshold is below the service's normal p95."),
  e("ev-backoff-spacing", "exponential-backoff", "LOG", "PRESENT",
    "retry delays with jitter",
    "Retry intervals spreading out — 100 ms, 230 ms, 870 ms — and differing between clients.",
    "Client retry logs from several instances, compared.",
    "Identical intervals across clients mean the jitter is missing, which is what turns a retry policy into a synchronised herd.",
    "Log timestamp granularity can hide small amounts of jitter."),
  e("ev-idempotency-dupes", "idempotency-key", "METRIC", "FLAT",
    "duplicate-key hits on write endpoints",
    "A steady trickle of requests matching a previously seen key and returning the original result.",
    "Idempotency-store hit counter, next to the client retry rate.",
    "It shows retries are being absorbed safely — the same evidence proves both that clients retry and that you survive it.",
    "A key generated per attempt instead of per logical operation produces zero hits while looking correct."),
  e("ev-pooler-saturation", "connection-pooler", "METRIC", "FLAT",
    "server-side connections vs client-side connections",
    "Thousands of client connections multiplexed onto a few dozen database connections.",
    "Pooler statistics (pgbouncer SHOW POOLS) next to database connection count.",
    "The ratio is the pooler's entire value proposition; if it approaches one, the pooler is a proxy and nothing more.",
    "Session-mode pooling cannot multiplex, so the ratio stays near one by design."),
  e("ev-coalescing-origin", "request-coalescing", "METRIC", "DOWN",
    "origin requests per cache miss",
    "A single origin request serving hundreds of waiting callers for the same key.",
    "Miss count against origin fetch count for the same cache.",
    "A ratio far below one is proof the single-flight lock is working, and it is the direct antidote to the stampede spike.",
    "Low concurrency makes the ratio look like one even when coalescing works correctly."),
];
