import type { Relationship, RelationshipType } from "../schema";

const r = (sourceId: string, type: RelationshipType, targetId: string): Relationship => ({
  id: `${sourceId}--${type.toLowerCase()}--${targetId}`,
  sourceId,
  targetId,
  type,
});

export const relationships: Relationship[] = [
  // Application
  r("n-plus-one", "CAUSES", "connection-pool-exhaustion"),
  r("n-plus-one", "AMPLIFIES", "tail-latency"),
  r("unbounded-query", "CAUSES", "full-table-scan"),
  r("unbounded-query", "CAUSES", "heap-pressure"),
  r("missing-pagination", "CAUSES", "unbounded-query"),
  r("hot-path-allocation", "CAUSES", "heap-pressure"),
  r("synchronous-fanout", "AMPLIFIES", "tail-latency"),
  r("synchronous-fanout", "CAUSES", "thread-pool-starvation"),
  // API & resilience
  r("retry-storm", "AMPLIFIES", "cascading-failure"),
  r("retry-storm", "CAUSES", "connection-pool-exhaustion"),
  r("retry-storm", "CAUSES", "queue-buildup"),
  r("thundering-herd", "CAUSES", "cache-stampede"),
  r("thundering-herd", "AMPLIFIES", "retry-storm"),
  r("missing-timeout", "CAUSES", "thread-pool-starvation"),
  r("missing-timeout", "CAUSES", "connection-pool-exhaustion"),
  r("exponential-backoff", "MITIGATES", "retry-storm"),
  r("exponential-backoff", "MITIGATES", "thundering-herd"),
  r("circuit-breaker", "MITIGATES", "cascading-failure"),
  r("circuit-breaker", "MITIGATES", "retry-storm"),
  r("circuit-breaker", "REQUIRES", "missing-timeout"),
  r("rate-limiting", "MITIGATES", "queue-buildup"),
  r("rate-limiting", "ALTERNATIVE_TO", "load-shedding"),
  r("idempotency-key", "REQUIRES", "exponential-backoff"),
  r("bulkhead", "MITIGATES", "thread-pool-starvation"),
  r("bulkhead", "MITIGATES", "cascading-failure"),
  // Data
  r("connection-pool-exhaustion", "CAUSES", "thread-pool-starvation"),
  r("connection-pool-exhaustion", "CAUSES", "queue-buildup"),
  r("lock-contention", "CAUSES", "connection-pool-exhaustion"),
  r("lock-contention", "CAUSES", "deadlock"),
  r("long-transaction", "CAUSES", "lock-contention"),
  r("long-transaction", "AMPLIFIES", "replication-lag"),
  r("missing-index", "CAUSES", "full-table-scan"),
  r("full-table-scan", "CAUSES", "page-cache-thrashing"),
  r("full-table-scan", "AMPLIFIES", "lock-contention"),
  r("query-plan-regression", "CAUSES", "full-table-scan"),
  r("write-amplification", "AMPLIFIES", "replication-lag"),
  r("missing-index", "TRADEOFF_OF", "write-amplification"),
  r("connection-pooler", "MITIGATES", "connection-pool-exhaustion"),
  r("connection-pooler", "MITIGATES", "connection-churn"),
  // Caching
  r("cache-stampede", "CAUSES", "connection-pool-exhaustion"),
  r("cache-stampede", "AMPLIFIES", "cascading-failure"),
  r("request-coalescing", "MITIGATES", "cache-stampede"),
  r("request-coalescing", "MITIGATES", "hot-key"),
  r("cold-cache", "CAUSES", "cache-stampede"),
  r("hot-key", "CAUSES", "noisy-neighbor"),
  r("cache-invalidation", "TRADEOFF_OF", "cache-stampede"),
  // Runtime
  r("heap-pressure", "CAUSES", "gc-pause"),
  r("memory-leak", "CAUSES", "heap-pressure"),
  r("gc-pause", "AMPLIFIES", "tail-latency"),
  r("gc-pause", "CAUSES", "missing-timeout"),
  r("thread-pool-starvation", "CAUSES", "queue-buildup"),
  r("event-loop-blocking", "AMPLIFIES", "tail-latency"),
  r("async-io", "MITIGATES", "thread-pool-starvation"),
  r("async-io", "TRADEOFF_OF", "event-loop-blocking"),
  r("async-io", "ALTERNATIVE_TO", "bulkhead"),
  // Network
  r("tcp-retransmits", "AMPLIFIES", "tail-latency"),
  r("tcp-retransmits", "CAUSES", "head-of-line-blocking"),
  r("tcp-retransmits", "CAUSES", "retry-storm"),
  r("head-of-line-blocking", "AMPLIFIES", "tail-latency"),
  r("dns-latency", "AMPLIFIES", "tail-latency"),
  r("connection-churn", "CAUSES", "tls-handshake-cost"),
  r("connection-churn", "CAUSES", "fd-exhaustion"),
  r("keep-alive", "MITIGATES", "connection-churn"),
  r("keep-alive", "MITIGATES", "tls-handshake-cost"),
  r("keep-alive", "AMPLIFIES", "head-of-line-blocking"),
  // OS
  r("cpu-throttling", "AMPLIFIES", "gc-pause"),
  r("cpu-throttling", "CAUSES", "thread-pool-starvation"),
  r("cpu-throttling", "AMPLIFIES", "tail-latency"),
  r("context-switching", "AMPLIFIES", "cpu-throttling"),
  r("fd-exhaustion", "CAUSES", "cascading-failure"),
  r("page-cache-thrashing", "AMPLIFIES", "tail-latency"),
  r("noisy-neighbor", "CAUSES", "cpu-throttling"),
  r("noisy-neighbor", "AMPLIFIES", "tail-latency"),
  // Distributed
  r("queue-buildup", "CAUSES", "missing-timeout"),
  r("queue-buildup", "AMPLIFIES", "cascading-failure"),
  r("load-shedding", "MITIGATES", "cascading-failure"),
  r("load-shedding", "MITIGATES", "queue-buildup"),
  r("backpressure", "MITIGATES", "queue-buildup"),
  r("backpressure", "ALTERNATIVE_TO", "load-shedding"),
  r("hedged-requests", "MITIGATES", "tail-latency"),
  r("hedged-requests", "REQUIRES", "idempotency-key"),
  r("hedged-requests", "AMPLIFIES", "retry-storm"),
];
