// The reference library. Every concept in the atlas points at primary material
// written by people who measured the behaviour, not at this file.
import type { ConceptSource, Source, SourceKind } from "../schema";

const s = (
  id: string,
  kind: SourceKind,
  title: string,
  author: string,
  year: number | undefined,
  url: string,
  note: string,
): Source => ({ id, kind, title, author, url, note, ...(year ? { year } : {}) });

export const sources: Source[] = [
  s("ddia", "BOOK", "Designing Data-Intensive Applications", "Martin Kleppmann", 2017,
    "https://dataintensive.net/",
    "The single best account of replication, transactions and the failure modes that live between them."),
  s("sre-book", "BOOK", "Site Reliability Engineering", "Beyer, Jones, Petoff & Murphy (Google)", 2016,
    "https://sre.google/sre-book/table-of-contents/",
    "Where overload, cascading failure and error budgets were first written down for a general audience."),
  s("sre-workbook", "BOOK", "The Site Reliability Workbook", "Beyer, Murphy, Rensin, Kawahara & Thorne (Google)", 2018,
    "https://sre.google/workbook/table-of-contents/",
    "The practical companion: SLOs, percentile targets and the arithmetic behind latency objectives."),
  s("release-it", "BOOK", "Release It! Design and Deploy Production-Ready Software", "Michael T. Nygard", 2018,
    "https://pragprog.com/titles/mnee2/release-it-second-edition/",
    "The stability patterns and antipatterns vocabulary — timeout, circuit breaker, bulkhead — in one place."),
  s("systems-performance", "BOOK", "Systems Performance: Enterprise and the Cloud", "Brendan Gregg", 2020,
    "https://www.brendangregg.com/systems-performance-2nd-edition-book.html",
    "The methodology and the counters: CPU, memory, file system, disk and network, each with the tool that shows it."),
  s("hpbn", "BOOK", "High Performance Browser Networking", "Ilya Grigorik", 2013,
    "https://hpbn.co/",
    "Free online. The clearest explanation of handshakes, keep-alive and head-of-line blocking on the wire."),
  s("tail-at-scale", "PAPER", "The Tail at Scale", "Jeffrey Dean & Luiz André Barroso", 2013,
    "https://cacm.acm.org/research/the-tail-at-scale/",
    "Why fan-out turns a rare slow response into a common one, and what hedging actually buys."),
  s("metastable-failures", "PAPER", "Metastable Failures in Distributed Systems", "Bronson, Aghayev, Charapko & Zhu", 2021,
    "https://sigops.org/s/conferences/hotos/2021/papers/hotos21-s11-bronson.pdf",
    "Names the state where load is gone but the system stays down: the sustaining effect outlives the trigger."),
  s("memcache-fb", "PAPER", "Scaling Memcache at Facebook", "Nishtala et al. (NSDI)", 2013,
    "https://www.usenix.org/system/files/conference/nsdi13/nsdi13-final170_update.pdf",
    "Leases, stale sets and hot keys — the paper that defined how large caches actually behave."),
  s("lsm-tree", "PAPER", "The Log-Structured Merge-Tree (LSM-Tree)", "Patrick O'Neil, Edward Cheng, Dieter Gawlick & Elizabeth O'Neil", 1996,
    "https://www.cs.umb.edu/~poneil/lsmtree.pdf",
    "The original write-amplification trade-off: cheap writes now, compaction work later."),
  s("littles-law", "ARTICLE", "Little's Law as Viewed on its 50th Anniversary", "John D. C. Little", 2011,
    "https://www.informs.org/content/download/255808/2414681/file/little.pdf",
    "L = λW. Pool sizing, thread counts and queue depth are all this one equation."),
  s("fail-at-scale", "ARTICLE", "Fail at Scale", "Ben Maurer (ACM Queue)", 2015,
    "https://queue.acm.org/detail.cfm?id=2839461",
    "Facebook's taxonomy of overload: thundering herds, poisoned caches and the controls that stop them."),
  s("backoff-jitter", "ARTICLE", "Exponential Backoff and Jitter", "Marc Brooker (AWS)", 2015,
    "https://aws.amazon.com/blogs/architecture/exponential-backoff-and-jitter/",
    "Shows with simulation why backoff without jitter still synchronises clients."),
  s("timeouts-retries", "ARTICLE", "Timeouts, Retries and Backoff with Jitter", "Marc Brooker (Amazon Builders' Library)", undefined,
    "https://aws.amazon.com/builders-library/timeouts-retries-and-backoff-with-jitter/",
    "Retry budgets and token buckets: how to retry without becoming the outage."),
  s("builders-load-shedding", "ARTICLE", "Using Load Shedding to Avoid Overload", "David Yanacek (Amazon Builders' Library)", undefined,
    "https://aws.amazon.com/builders-library/using-load-shedding-to-avoid-overload/",
    "Why a fast rejection is a better answer than a slow success, and where to put the decision."),
  s("builders-queue-backlogs", "ARTICLE", "Avoiding Insurmountable Queue Backlogs", "David Yanacek (Amazon Builders' Library)", undefined,
    "https://aws.amazon.com/builders-library/avoiding-insurmountable-queue-backlogs/",
    "Queues hide overload until the backlog is longer than the useful lifetime of its contents."),
  s("builders-fairness", "ARTICLE", "Fairness in Multi-Tenant Systems", "David Yanacek (Amazon Builders' Library)", undefined,
    "https://aws.amazon.com/builders-library/fairness-in-multi-tenant-systems/",
    "How one tenant's workload becomes everyone's latency, and the quota mechanics that prevent it."),
  s("caching-strategies", "ARTICLE", "Caching Challenges and Strategies", "Matt Brinkley & Jas Chhabra (Amazon Builders' Library)", undefined,
    "https://aws.amazon.com/builders-library/caching-challenges-and-strategies/",
    "Modality, cold caches and the bimodal behaviour a cache introduces into a system."),
  s("fowler-circuit-breaker", "ARTICLE", "CircuitBreaker", "Martin Fowler", 2014,
    "https://martinfowler.com/bliki/CircuitBreaker.html",
    "The canonical description of the three states and what the half-open probe is for."),
  s("stripe-rate-limiters", "ARTICLE", "Scaling Your API with Rate Limiters", "Paul Tarjan (Stripe)", 2017,
    "https://stripe.com/blog/rate-limiters",
    "Four limiter types in production, including load shedders that protect critical traffic first."),
  s("timewait-bernat", "ARTICLE", "Coping with the TCP TIME-WAIT State on Busy Linux Servers", "Vincent Bernat", 2014,
    "https://vincent.bernat.ch/en/blog/2014-tcp-time-wait-state-linux",
    "What TIME-WAIT costs, why the usual sysctl advice is wrong, and when connection churn actually bites."),
  s("use-method", "ARTICLE", "The USE Method", "Brendan Gregg", 2012,
    "https://www.brendangregg.com/usemethod.html",
    "Utilisation, saturation, errors — a checklist that finds resource bottlenecks without guesswork."),
  s("use-the-index-luke", "ARTICLE", "Use The Index, Luke!", "Markus Winand", undefined,
    "https://use-the-index-luke.com/",
    "SQL indexing explained from the developer's side: what the plan does with your WHERE clause."),
  s("no-offset", "ARTICLE", "Pagination Done the PostgreSQL Way (No Offset)", "Markus Winand", undefined,
    "https://use-the-index-luke.com/no-offset",
    "Why OFFSET pagination degrades with depth and what keyset pagination replaces it with."),
  s("rfc6298", "RFC", "RFC 6298: Computing TCP's Retransmission Timer", "Paxson, Allman, Chu & Sargent (IETF)", 2011,
    "https://www.rfc-editor.org/rfc/rfc6298",
    "Defines RTO: the minimum one-second floor that makes a single lost packet so expensive."),
  s("rfc5681", "RFC", "RFC 5681: TCP Congestion Control", "Allman, Paxson & Blanton (IETF)", 2009,
    "https://www.rfc-editor.org/rfc/rfc5681",
    "Slow start, congestion avoidance and fast retransmit — why throughput collapses on loss."),
  s("rfc9112", "RFC", "RFC 9112: HTTP/1.1", "Fielding, Nottingham & Reschke (IETF)", 2022,
    "https://www.rfc-editor.org/rfc/rfc9112#name-persistence",
    "The persistence section: what a connection may be reused for and when it must be closed."),
  s("rfc9113", "RFC", "RFC 9113: HTTP/2", "Thomson & Benfield (IETF)", 2022,
    "https://www.rfc-editor.org/rfc/rfc9113",
    "Multiplexing removes application-level head-of-line blocking but not the TCP-level kind."),
  s("rfc9000", "RFC", "RFC 9000: QUIC", "Iyengar & Thomson (IETF)", 2021,
    "https://www.rfc-editor.org/rfc/rfc9000",
    "Per-stream delivery over UDP: the transport answer to head-of-line blocking."),
  s("rfc8446", "RFC", "RFC 8446: TLS 1.3", "Eric Rescorla (IETF)", 2018,
    "https://www.rfc-editor.org/rfc/rfc8446",
    "One round trip for a full handshake, zero for resumption — the numbers behind handshake cost."),
  s("rfc1035", "RFC", "RFC 1035: Domain Names — Implementation and Specification", "Paul Mockapetris (IETF)", 1987,
    "https://www.rfc-editor.org/rfc/rfc1035",
    "TTL semantics and resolver behaviour, which is where most surprising DNS latency comes from."),
  s("pg-explain", "DOCS", "PostgreSQL: Using EXPLAIN", "PostgreSQL Global Development Group", undefined,
    "https://www.postgresql.org/docs/current/using-explain.html",
    "How to read a plan, and why EXPLAIN (ANALYZE, BUFFERS) is the only version worth trusting."),
  s("pg-mvcc", "DOCS", "PostgreSQL: Concurrency Control (MVCC)", "PostgreSQL Global Development Group", undefined,
    "https://www.postgresql.org/docs/current/mvcc.html",
    "Snapshots, xmin horizons and the reason one idle transaction can bloat a whole table."),
  s("pg-explicit-locking", "DOCS", "PostgreSQL: Explicit Locking", "PostgreSQL Global Development Group", undefined,
    "https://www.postgresql.org/docs/current/explicit-locking.html",
    "The lock conflict matrix and the deadlock detector's behaviour, stated precisely."),
  s("pg-stat-statements", "DOCS", "PostgreSQL: pg_stat_statements", "PostgreSQL Global Development Group", undefined,
    "https://www.postgresql.org/docs/current/pgstatstatements.html",
    "Per-statement totals, mean times and row counts: the first place to look for a regression."),
  s("pg-hot-standby", "DOCS", "PostgreSQL: Hot Standby", "PostgreSQL Global Development Group", undefined,
    "https://www.postgresql.org/docs/current/hot-standby.html",
    "Replay lag, conflicts and the trade-off between replica freshness and query cancellation."),
  s("pgbouncer", "DOCS", "PgBouncer Features", "PgBouncer maintainers", undefined,
    "https://www.pgbouncer.org/features.html",
    "Pooling modes and their constraints — transaction pooling is not a drop-in for session state."),
  s("jvm-gc-tuning", "DOCS", "HotSpot Virtual Machine Garbage Collection Tuning Guide", "Oracle", undefined,
    "https://docs.oracle.com/en/java/javase/21/gctuning/index.html",
    "Collector choices, pause-time goals and what allocation rate does to each of them."),
  s("nodejs-event-loop", "DOCS", "The Node.js Event Loop", "Node.js contributors", undefined,
    "https://nodejs.org/en/learn/asynchronous-work/event-loop-timers-and-nexttick",
    "Phase order and the cost of holding the loop — required reading before blaming the database."),
  s("epoll-man", "DOCS", "epoll(7) — Linux manual page", "Linux man-pages project", undefined,
    "https://man7.org/linux/man-pages/man7/epoll.7.html",
    "The readiness interface every async runtime sits on, level- versus edge-triggered."),
  s("getrlimit-man", "DOCS", "getrlimit(2) — Linux manual page", "Linux man-pages project", undefined,
    "https://man7.org/linux/man-pages/man2/getrlimit.2.html",
    "RLIMIT_NOFILE and friends: the ceilings that turn into EMFILE at the worst moment."),
  s("cfs-bandwidth", "DOCS", "CFS Bandwidth Control", "Linux kernel documentation", undefined,
    "https://docs.kernel.org/scheduler/sched-bwc.html",
    "Quota, period and throttled time — the mechanism behind container CPU throttling."),
  s("cgroup-v2", "DOCS", "Control Group v2", "Linux kernel documentation", undefined,
    "https://docs.kernel.org/admin-guide/cgroup-v2.html",
    "How CPU, memory and I/O are actually partitioned between tenants on one host."),
  s("stripe-idempotency", "DOCS", "Idempotent Requests", "Stripe", undefined,
    "https://docs.stripe.com/api/idempotent_requests",
    "A production idempotency contract: key scope, result caching and the 24-hour window."),
  s("resilience4j-bulkhead", "DOCS", "Resilience4j: Bulkhead", "Resilience4j maintainers", undefined,
    "https://resilience4j.readme.io/docs/bulkhead",
    "Semaphore and thread-pool isolation, with the configuration knobs that make it real."),
  s("rails-querying", "DOCS", "Active Record Query Interface: Eager Loading", "Ruby on Rails contributors", undefined,
    "https://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations",
    "The ORM side of N+1: how lazy association loading produces a query per row."),
  s("reactive-streams", "SPEC", "Reactive Streams Specification", "Reactive Streams contributors", 2015,
    "https://www.reactive-streams.org/",
    "Demand-driven flow control: the formal version of 'the consumer sets the pace'."),
  s("otel-semconv", "SPEC", "OpenTelemetry Semantic Conventions", "OpenTelemetry Authors", undefined,
    "https://opentelemetry.io/docs/specs/semconv/",
    "The names the evidence cards use, so a signal means the same thing across stacks."),
];

const l = (conceptId: string, sourceId: string, relevance: string): ConceptSource => ({
  conceptId,
  sourceId,
  relevance,
});

export const conceptSources: ConceptSource[] = [
  // ------------------------------------------------------------- application
  l("n-plus-one", "rails-querying", "The eager-loading section shows the exact lazy-association pattern that generates the extra queries."),
  l("n-plus-one", "otel-semconv", "Database client span conventions give you the per-request query count without custom instrumentation."),
  l("unbounded-query", "use-the-index-luke", "Explains why a query that returns everything cannot be fixed with an index."),
  l("unbounded-query", "pg-stat-statements", "The rows/calls ratio is the cheapest way to find result sets that grew over time."),
  l("missing-pagination", "no-offset", "Makes the case for keyset pagination with the cost curve of deep OFFSET."),
  l("missing-pagination", "use-the-index-luke", "Covers the index support a keyset predicate needs to stay fast."),
  l("hot-path-allocation", "systems-performance", "Chapter 7 connects allocation rate to memory bandwidth and collector pressure."),
  l("hot-path-allocation", "jvm-gc-tuning", "Allocation rate is the input variable for every pause-time goal in the guide."),
  l("synchronous-fanout", "tail-at-scale", "Quantifies how a 1-in-100 slow response becomes a 1-in-2 slow request under fan-out."),
  l("synchronous-fanout", "release-it", "The integration-point chapter on how one slow dependency blocks a whole request path."),

  // --------------------------------------------------------------------- api
  l("retry-storm", "backoff-jitter", "Simulations showing that backoff alone still leaves clients synchronised."),
  l("retry-storm", "timeouts-retries", "Retry budgets and client-side token buckets, with the failure they prevent."),
  l("retry-storm", "metastable-failures", "Retries are the classic sustaining effect that keeps a system down after the trigger is gone."),
  l("thundering-herd", "fail-at-scale", "Describes the herd that forms the moment a shared dependency recovers."),
  l("thundering-herd", "memcache-fb", "Leases exist specifically to stop a herd of clients regenerating the same value."),
  l("missing-timeout", "timeouts-retries", "How to pick a timeout from the latency distribution instead of a round number."),
  l("missing-timeout", "release-it", "The timeout pattern and the resource leak that an unbounded wait causes."),
  l("exponential-backoff", "backoff-jitter", "The jitter variants compared, including why full jitter usually wins."),
  l("exponential-backoff", "timeouts-retries", "Places backoff inside a complete retry policy rather than treating it as the whole answer."),
  l("circuit-breaker", "fowler-circuit-breaker", "The three states and the half-open probe, in the clearest short form."),
  l("circuit-breaker", "release-it", "Where the breaker belongs in a system and what it must do with the rejected call."),
  l("rate-limiting", "stripe-rate-limiters", "Four limiter types deployed together, with the reasoning for each."),
  l("rate-limiting", "builders-fairness", "Per-tenant quotas as the fairness mechanism rather than a global ceiling."),
  l("idempotency-key", "stripe-idempotency", "A real contract: key scope, stored response, and the retry window."),
  l("idempotency-key", "ddia", "Chapter 11 on exactly-once semantics being built from deduplication, not from magic."),
  l("bulkhead", "resilience4j-bulkhead", "Semaphore versus thread-pool isolation with concrete configuration."),
  l("bulkhead", "release-it", "The bulkhead pattern as damage containment, drawn from ship design."),

  // -------------------------------------------------------------------- data
  l("connection-pool-exhaustion", "littles-law", "Pool size is λ×W: the law tells you the number before you guess it."),
  l("connection-pool-exhaustion", "pgbouncer", "What happens on the database side when the application pool is already too large."),
  l("lock-contention", "pg-explicit-locking", "The conflict matrix that decides which statement waits for which."),
  l("lock-contention", "ddia", "Chapter 7 on isolation levels and the concurrency they trade away."),
  l("missing-index", "use-the-index-luke", "Index selection from the query's perspective, including composite column order."),
  l("missing-index", "pg-explain", "How a sequential scan appears in the plan and what the row estimate tells you."),
  l("full-table-scan", "pg-explain", "Reading scan nodes, row estimates and buffer counts in a real plan."),
  l("full-table-scan", "use-the-index-luke", "When a full scan is correct and when it is a missing index in disguise."),
  l("long-transaction", "pg-mvcc", "Snapshot visibility and the xmin horizon that an idle transaction pins."),
  l("long-transaction", "pg-explicit-locking", "Locks held to commit: why transaction length is lock duration."),
  l("deadlock", "pg-explicit-locking", "Deadlock detection, the timeout that triggers it, and consistent lock ordering."),
  l("deadlock", "ddia", "Chapter 7 on deadlock as a property of concurrent access patterns, not of bad luck."),
  l("replication-lag", "ddia", "Chapter 5 on read-your-writes, monotonic reads and the anomalies lag produces."),
  l("replication-lag", "pg-hot-standby", "Replay lag measurement and the conflicts that make a replica cancel queries."),
  l("connection-pooler", "pgbouncer", "Pooling modes and the session-state constraints each one imposes."),
  l("connection-pooler", "littles-law", "Sizing the pool behind the pooler with the same arithmetic, one layer down."),
  l("query-plan-regression", "pg-explain", "Comparing two plans for the same statement, which is the whole diagnosis."),
  l("query-plan-regression", "pg-stat-statements", "Mean time per statement over time is how a regression announces itself."),
  l("write-amplification", "lsm-tree", "The original analysis of deferring write cost into compaction."),
  l("write-amplification", "ddia", "Chapter 3 compares B-tree and LSM write amplification with their trade-offs."),

  // ----------------------------------------------------------------- caching
  l("cache-stampede", "memcache-fb", "Leases as the production answer to many clients missing the same key at once."),
  l("cache-stampede", "caching-strategies", "The bimodal behaviour a cache adds, and the failure it hides until expiry."),
  l("request-coalescing", "memcache-fb", "One regeneration per key while everyone else waits for the result."),
  l("request-coalescing", "caching-strategies", "Where coalescing belongs relative to the cache and the origin."),
  l("cold-cache", "caching-strategies", "Why a cold cache is a capacity problem, not a latency problem."),
  l("cold-cache", "sre-book", "The overload chapter on recovery traffic exceeding steady-state capacity."),
  l("hot-key", "memcache-fb", "Key-level hot spots and the replication tricks used to spread them."),
  l("hot-key", "builders-fairness", "One tenant's hot key as a fairness failure across a shared cache."),
  l("cache-invalidation", "caching-strategies", "Invalidation strategies and the staleness each one accepts."),
  l("cache-invalidation", "ddia", "Chapter 11 on derived data staying consistent with its source."),

  // ----------------------------------------------------------------- runtime
  l("gc-pause", "jvm-gc-tuning", "Collector-by-collector pause behaviour and the goals you can actually set."),
  l("gc-pause", "systems-performance", "Measuring pauses from outside the runtime, where they look like latency."),
  l("heap-pressure", "jvm-gc-tuning", "Heap sizing, promotion failures and the collector's response to pressure."),
  l("heap-pressure", "systems-performance", "Memory saturation signals at the OS level before the process dies."),
  l("memory-leak", "systems-performance", "Chapter 7 separates a leak from growth and shows how to attribute both."),
  l("memory-leak", "jvm-gc-tuning", "Why a leak shows up as rising post-collection live-set, not as allocation rate."),
  l("thread-pool-starvation", "littles-law", "The thread count a given arrival rate and service time require."),
  l("thread-pool-starvation", "release-it", "Blocked threads as the most common path to an unresponsive service."),
  l("event-loop-blocking", "nodejs-event-loop", "Phase order and what holding the loop does to every pending callback."),
  l("event-loop-blocking", "systems-performance", "Profiling the synchronous frame that is holding the stack."),
  l("async-io", "epoll-man", "The readiness interface underneath every async runtime, level- versus edge-triggered."),
  l("async-io", "nodejs-event-loop", "How readiness becomes callbacks, and which work still runs on a thread pool."),

  // ----------------------------------------------------------------- network
  l("tcp-retransmits", "rfc6298", "The retransmission timer and the minimum RTO that makes a lost packet expensive."),
  l("tcp-retransmits", "rfc5681", "Fast retransmit, fast recovery and the congestion window response to loss."),
  l("tcp-retransmits", "systems-performance", "Which counters to read, and the difference between retransmits and drops."),
  l("head-of-line-blocking", "rfc9113", "HTTP/2 multiplexing removes the application-level form but not the transport one."),
  l("head-of-line-blocking", "rfc9000", "QUIC's per-stream delivery, the transport fix for the remaining case."),
  l("head-of-line-blocking", "hpbn", "The protocol history that explains why six connections per origin ever made sense."),
  l("dns-latency", "rfc1035", "TTL semantics and resolver behaviour, the source of most surprising lookup latency."),
  l("dns-latency", "hpbn", "Where lookups sit in the connection timeline and what prefetching can remove."),
  l("connection-churn", "timewait-bernat", "What TIME-WAIT actually costs and which sysctl advice is wrong."),
  l("connection-churn", "hpbn", "Setup cost per connection, which is the reason churn matters at all."),
  l("keep-alive", "rfc9112", "The persistence rules: what may be reused and when a connection must close."),
  l("keep-alive", "hpbn", "Idle-timeout tuning across client, server and every proxy in between."),
  l("tls-handshake-cost", "rfc8446", "One round trip for a full handshake, zero for resumption, with the caveats."),
  l("tls-handshake-cost", "hpbn", "Handshake cost in real latency terms, including session resumption behaviour."),

  // ---------------------------------------------------------------------- os
  l("cpu-throttling", "cfs-bandwidth", "Quota, period and throttled time — the exact mechanism and its counters."),
  l("cpu-throttling", "cgroup-v2", "Where the limit is configured and how it interacts with the rest of the host."),
  l("context-switching", "systems-performance", "Voluntary versus involuntary switches and what each one tells you."),
  l("context-switching", "use-method", "Saturation as the signal that the run queue, not the CPU, is the problem."),
  l("fd-exhaustion", "getrlimit-man", "The limits themselves, and which syscalls return EMFILE when you hit them."),
  l("fd-exhaustion", "epoll-man", "Why an event-driven server holds so many descriptors at once."),
  l("page-cache-thrashing", "systems-performance", "Chapter 8 on the file-system cache, hit ratios and the fall off the cliff."),
  l("page-cache-thrashing", "use-method", "Memory saturation signals: scan rate and major faults before latency moves."),
  l("noisy-neighbor", "builders-fairness", "Multi-tenant interference framed as a fairness problem with quota answers."),
  l("noisy-neighbor", "cgroup-v2", "The isolation primitives available when fairness must be enforced on one host."),

  // ------------------------------------------------------------- distributed
  l("cascading-failure", "metastable-failures", "The sustaining effect that keeps a system down after the trigger clears."),
  l("cascading-failure", "fail-at-scale", "Real cascades and the controls that stopped them at Facebook scale."),
  l("cascading-failure", "sre-book", "The addressing-cascading-failures chapter, including how to break the loop."),
  l("load-shedding", "builders-load-shedding", "Why a fast rejection beats a slow success and where the decision belongs."),
  l("load-shedding", "sre-book", "Criticality-aware shedding so the important traffic survives the cut."),
  l("backpressure", "reactive-streams", "Demand-driven flow control specified precisely enough to implement."),
  l("backpressure", "builders-queue-backlogs", "What happens when there is no backpressure: the queue absorbs it until it cannot."),
  l("queue-buildup", "builders-queue-backlogs", "Backlogs that outlive the usefulness of their contents, and how to bound them."),
  l("queue-buildup", "littles-law", "Wait time is queue length over throughput; the backlog predicts the latency."),
  l("tail-latency", "tail-at-scale", "The paper that made p99 a design constraint rather than a reporting detail."),
  l("tail-latency", "sre-workbook", "Turning percentile targets into SLOs you can actually operate against."),
  l("tail-latency", "otel-semconv", "Histogram conventions so percentiles stay comparable across services."),
  l("hedged-requests", "tail-at-scale", "Hedging and tied requests, with the measured effect on p99 and on load."),
  l("hedged-requests", "sre-workbook", "The cost side: extra load in exchange for a shorter tail."),
];
