/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as ConceptsSlugRouteImport } from './routes/concepts.$slug'
import { Route as IncidentsIndexRouteImport } from './routes/incidents.index'
import { Route as IncidentsSlugRouteImport } from './routes/incidents.$slug'
import { Route as ApiAiDiagnoseRouteImport } from './routes/api/ai/diagnose'
import { Route as ApiAiExplainRouteImport } from './routes/api/ai/explain'
import { Route as ApiAiResearchRouteImport } from './routes/api/ai/research'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const ConceptsSlugRoute = ConceptsSlugRouteImport.update({
  id: '/concepts/$slug',
  path: '/concepts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsIndexRoute = IncidentsIndexRouteImport.update({
  id: '/incidents/',
  path: '/incidents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IncidentsSlugRoute = IncidentsSlugRouteImport.update({
  id: '/incidents/$slug',
  path: '/incidents/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiDiagnoseRoute = ApiAiDiagnoseRouteImport.update({
  id: '/api/ai/diagnose',
  path: '/api/ai/diagnose',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiExplainRoute = ApiAiExplainRouteImport.update({
  id: '/api/ai/explain',
  path: '/api/ai/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiResearchRoute = ApiAiResearchRouteImport.update({
  id: '/api/ai/research',
  path: '/api/ai/research',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/triage': typeof TriageRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/incidents/$slug': typeof IncidentsSlugRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/ai/diagnose': typeof ApiAiDiagnoseRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/research': typeof ApiAiResearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/triage': typeof TriageRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/incidents/$slug': typeof IncidentsSlugRoute
  '/incidents': typeof IncidentsIndexRoute
  '/api/ai/diagnose': typeof ApiAiDiagnoseRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/research': typeof ApiAiResearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/evidence': typeof EvidenceRoute
  '/graph': typeof GraphRoute
  '/learn': typeof LearnRoute
  '/library': typeof LibraryRoute
  '/research': typeof ResearchRoute
  '/search': typeof SearchRoute
  '/triage': typeof TriageRoute
  '/concepts/$slug': typeof ConceptsSlugRoute
  '/incidents/$slug': typeof IncidentsSlugRoute
  '/incidents/': typeof IncidentsIndexRoute
  '/api/ai/diagnose': typeof ApiAiDiagnoseRoute
  '/api/ai/explain': typeof ApiAiExplainRoute
  '/api/ai/research': typeof ApiAiResearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/evidence'
    | '/graph'
    | '/learn'
    | '/library'
    | '/research'
    | '/search'
    | '/triage'
    | '/concepts/$slug'
    | '/incidents/$slug'
    | '/incidents/'
    | '/api/ai/diagnose'
    | '/api/ai/explain'
    | '/api/ai/research'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/evidence'
    | '/graph'
    | '/learn'
    | '/library'
    | '/research'
    | '/search'
    | '/triage'
    | '/concepts/$slug'
    | '/incidents/$slug'
    | '/incidents'
    | '/api/ai/diagnose'
    | '/api/ai/explain'
    | '/api/ai/research'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/evidence'
    | '/graph'
    | '/learn'
    | '/library'
    | '/research'
    | '/search'
    | '/triage'
    | '/concepts/$slug'
    | '/incidents/$slug'
    | '/incidents/'
    | '/api/ai/diagnose'
    | '/api/ai/explain'
    | '/api/ai/research'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  EvidenceRoute: typeof EvidenceRoute
  GraphRoute: typeof GraphRoute
  LearnRoute: typeof LearnRoute
  LibraryRoute: typeof LibraryRoute
  ResearchRoute: typeof ResearchRoute
  SearchRoute: typeof SearchRoute
  TriageRoute: typeof TriageRoute
  ConceptsSlugRoute: typeof ConceptsSlugRoute
  IncidentsSlugRoute: typeof IncidentsSlugRoute
  IncidentsIndexRoute: typeof IncidentsIndexRoute
  ApiAiDiagnoseRoute: typeof ApiAiDiagnoseRoute
  ApiAiExplainRoute: typeof ApiAiExplainRoute
  ApiAiResearchRoute: typeof ApiAiResearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concepts/$slug': {
      id: '/concepts/$slug'
      path: '/concepts/$slug'
      fullPath: '/concepts/$slug'
      preLoaderRoute: typeof ConceptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/': {
      id: '/incidents/'
      path: '/incidents'
      fullPath: '/incidents/'
      preLoaderRoute: typeof IncidentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/incidents/$slug': {
      id: '/incidents/$slug'
      path: '/incidents/$slug'
      fullPath: '/incidents/$slug'
      preLoaderRoute: typeof IncidentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/diagnose': {
      id: '/api/ai/diagnose'
      path: '/api/ai/diagnose'
      fullPath: '/api/ai/diagnose'
      preLoaderRoute: typeof ApiAiDiagnoseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/explain': {
      id: '/api/ai/explain'
      path: '/api/ai/explain'
      fullPath: '/api/ai/explain'
      preLoaderRoute: typeof ApiAiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/research': {
      id: '/api/ai/research'
      path: '/api/ai/research'
      fullPath: '/api/ai/research'
      preLoaderRoute: typeof ApiAiResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  EvidenceRoute: EvidenceRoute,
  GraphRoute: GraphRoute,
  LearnRoute: LearnRoute,
  LibraryRoute: LibraryRoute,
  ResearchRoute: ResearchRoute,
  SearchRoute: SearchRoute,
  TriageRoute: TriageRoute,
  ConceptsSlugRoute: ConceptsSlugRoute,
  IncidentsSlugRoute: IncidentsSlugRoute,
  IncidentsIndexRoute: IncidentsIndexRoute,
  ApiAiDiagnoseRoute: ApiAiDiagnoseRoute,
  ApiAiExplainRoute: ApiAiExplainRoute,
  ApiAiResearchRoute: ApiAiResearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
